import React,{useEffect,useState} from 'react';
import { Alert,ScrollView,Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import { Card,Button,PageTitle,Label } from '../components/ui';
import { theme as t } from '../theme';
import { supabase } from '../lib/supabase';
import { api } from '../lib/api';
type FileItem={uri:string;name:string;type:string;kind:'identity'|'address_proof'};
export default function Kyc(){const [files,setFiles]=useState<FileItem[]>([]);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('Ikke sendt');useEffect(()=>{api<{submissions:{status:string}[]}>('/v1/kyc/status').then(r=>{const s=r.submissions[0]?.status;if(s)setStatus(s==='pending'?'Venter på godkjenning':s)}).catch(()=>{})},[]);
 async function pick(kind:FileItem['kind'],camera=false){if(camera){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){Alert.alert('Kameratilgang nødvendig');return}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.85});if(!r.canceled)setFiles(f=>[...f,{uri:r.assets[0].uri,name:`document-${Date.now()}.jpg`,type:'image/jpeg',kind}])}else{const r=await DocumentPicker.getDocumentAsync({type:['image/jpeg','image/png','image/webp','application/pdf'],copyToCacheDirectory:true});if(!r.canceled)setFiles(f=>[...f,{uri:r.assets[0].uri,name:r.assets[0].name,type:r.assets[0].mimeType||'application/pdf',kind}])}}
 async function submit(){if(!supabase){setStatus('Konfigurer Supabase før innsending');return}setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw Error('Logg inn først.');const refs=[];for(const file of files){const resp=await fetch(file.uri);const blob=await resp.blob();if(blob.size>10*1024*1024)throw Error('Hver fil må være under 10 MB.');const path=`${user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('kyc-private').upload(path,blob,{contentType:file.type,upsert:false});if(error)throw error;refs.push({path,kind:file.kind})}await api('/v1/kyc/submissions',{method:'POST',body:JSON.stringify({documents:refs})});setStatus('Venter på godkjenning');setFiles([])}catch(e){setStatus(e instanceof Error?e.message:'Innsending feilet')}finally{setBusy(false)}}
 return <SafeAreaView style={{flex:1,backgroundColor:t.color.bg}}><ScrollView contentContainerStyle={{padding:22,gap:15}}><PageTitle eyebrow="IDENTITET" title="Bekreft profilen" sub="Dokumentkrav avhenger av land og nummertype. Last opp kun det som trengs for ditt valg."/><Card><Label>STATUS</Label><Text style={{color:t.color.green,fontWeight:'800',fontSize:18,marginTop:9}}>{status}</Text></Card><Button title="Ta bilde av ID" secondary onPress={()=>pick('identity',true)}/><Button title="Velg ID-fil" secondary onPress={()=>pick('identity')}/><Button title="Ta bilde av adressebevis" secondary onPress={()=>pick('address_proof',true)}/><Button title="Velg adressebevis" secondary onPress={()=>pick('address_proof')}/>{files.map(f=><Text key={f.uri} style={{color:t.color.muted}}>↗ {f.kind==='identity'?'ID':'Adressebevis'} · {f.name}</Text>)}<Button title="Send til gjennomgang" onPress={submit} loading={busy} disabled={!files.length}/><Text style={{color:t.color.dim,fontSize:12,lineHeight:18}}>Dokumenter lagres i privat lagring. De deles kun med behandlingen av nummerkravet i henhold til Vedøys personvernregler.</Text></ScrollView></SafeAreaView>}
