import React,{useEffect,useMemo,useState} from 'react';
import { Alert,ScrollView,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Card,Button,Field,Label,PageTitle } from './components/ui';
import { theme as t } from './theme';
import { api } from './lib/api';
type Country={countryCode:string;country:string;numberTypes:string[];numberSearchAvailable:boolean;outboundVoicePolicyEnabled:boolean;outboundSmsPolicyEnabled:boolean;mobileData:false};
type Phone={phoneNumber:string;friendlyName:string;locality?:string;numberType:string;countryCode:string;capabilities:{voice:boolean;sms:boolean;mms:boolean};addressRequirements:string;monthlyPrice:string|null;currency:string|null};
type CountryCapabilities={numberTypes:{type:string;available:boolean;exampleCapabilities:{voice:boolean;sms:boolean;mms:boolean}|null;addressRequirements:string|null}[];internationalVoice:string;internationalSms:string;mobileData:false;note:string};
type Price={monthlyPrice:string;currency:string};
const labelType=(x:string)=>x==='tollFree'?'Toll-free':x==='local'?'Lokalt':x==='mobile'?'Mobil':x;
export default function NumberShopScreen(){
 const [countries,setCountries]=useState<Country[]>([]);const [country,setCountry]=useState<Country|null>(null);const [countrySearch,setCountrySearch]=useState('');const [countryInfo,setCountryInfo]=useState<CountryCapabilities|null>(null);const [prices,setPrices]=useState<Record<string,Price>>({});const [type,setType]=useState('local');const [numbers,setNumbers]=useState<Phone[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [query,setQuery]=useState('');
 useEffect(()=>{api<{countries:Country[]}>('/v1/numbers/countries').then(x=>{setCountries(x.countries);setCountry(x.countries.find(c=>c.countryCode==='NO')??x.countries[0]??null)}).catch(e=>setNotice(e.message))},[]);
 useEffect(()=>{if(!country)return;setCountryInfo(null);setPrices({});Promise.all([api<CountryCapabilities>(`/v1/numbers/countries/${country.countryCode}/capabilities`),api<{prices:Record<string,Price>}>(`/v1/numbers/countries/${country.countryCode}/pricing`)]).then(([info,priceInfo])=>{setCountryInfo(info);setPrices(priceInfo.prices)}).catch(()=>{})},[country]);
 const matches=useMemo(()=>{const filtered=countries.filter(c=>`${c.country} ${c.countryCode}`.toLowerCase().includes(countrySearch.toLowerCase()));if(countrySearch)return filtered.slice(0,8);return country?[country,...filtered.filter(c=>c.countryCode!==country.countryCode).slice(0,7)]:filtered.slice(0,8)},[countries,countrySearch,country]);
 async function search(){if(!country)return;setBusy(true);setNotice('');try{const p=new URLSearchParams({country:country.countryCode,type});if(query)p.set('contains',query);const d=await api<{numbers:Phone[]}>(`/v1/numbers/available?${p}`);setNumbers(d.numbers);if(!d.numbers.length)setNotice('Ingen numre funnet med disse filtrene.')}catch(e){setNotice(e instanceof Error?e.message:'Søk feilet')}finally{setBusy(false)}}
 function buy(n:Phone){if(!n.monthlyPrice||!n.currency){setNotice('Oppdatert månedspris mangler. Numre kan ikke bestilles før prisen kan bekreftes.');return}const amount=`${n.monthlyPrice} ${n.currency}`;Alert.alert('Bekreft nummerleie',`${n.phoneNumber}\n\nTwilio-beløp: ${amount} per måned, belastet den tilknyttede Twilio-kontoen. Samtale- og SMS-bruk faktureres separat.`,[{text:'Avbryt',style:'cancel'},{text:'Bekreft leie',onPress:async()=>{setBusy(true);setNotice('');try{await api('/v1/numbers/purchase',{method:'POST',body:JSON.stringify({phoneNumber:n.phoneNumber,countryCode:country!.countryCode,numberType:type,confirmedMonthlyPrice:n.monthlyPrice,currency:n.currency})});setNotice(`${n.phoneNumber} er lagt til linjene dine.`);setNumbers([])}catch(e){setNotice(e instanceof Error?e.message:'Kjøpet feilet')}finally{setBusy(false)}}}])}
 return <SafeAreaView style={{flex:1,backgroundColor:t.color.bg}}><ScrollView contentContainerStyle={{padding:22,gap:14}}><PageTitle eyebrow="NUMMERSHOP" title="Finn din linje" sub="Velg land og nummerklasse. Lager, funksjoner og pris hentes fra Twilio før bestilling."/><Card style={{gap:12}}><Label>VELG LAND · {countries.length} LAND</Label><Field value={countrySearch} onChangeText={setCountrySearch} placeholder={country?.country??'Søk etter land'}/><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{matches.map(c=><Text key={c.countryCode} onPress={()=>{setCountry(c);setCountrySearch('');setNumbers([]);setType(c.numberTypes[0]??'local')}} style={{color:country?.countryCode===c.countryCode?t.color.bg:t.color.text,backgroundColor:country?.countryCode===c.countryCode?t.color.green:t.color.raised,padding:9,borderRadius:10,overflow:'hidden'}}>{c.country} · {c.countryCode}</Text>)}</View><Text style={{color:t.color.muted,fontSize:12,lineHeight:18}}>Nummervalg: {country?.numberSearchAvailable?'Twilio-katalog tilgjengelig':'ikke tilgjengelig i denne Twilio-kontoen'} · Mobildata: nei (krever mobilabonnement/SIM/eSIM).</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{(country?.numberTypes??[]).map(x=><Text key={x} onPress={()=>setType(x)} style={{color:type===x?t.color.bg:t.color.text,backgroundColor:type===x?t.color.green:t.color.raised,padding:10,borderRadius:12,overflow:'hidden'}}>{labelType(x)}</Text>)}</View><Text style={{color:t.color.text,fontSize:13,fontWeight:'700'}}>Twilio leiepris {prices[type]?`· ${prices[type].monthlyPrice} ${prices[type].currency} / måned`:'· pris vises ved søkeresultat'}</Text>
 {countryInfo?.numberTypes.map(item=><View key={item.type} style={{paddingVertical:7,borderTopWidth:1,borderTopColor:t.color.border,gap:4}}><Text style={{color:t.color.text,fontWeight:'700'}}>{labelType(item.type)} · {item.available?'søkbar':'ingen katalogoppføring'}</Text><Text style={{color:t.color.muted,fontSize:12}}>Eksempelnummer: tale {item.exampleCapabilities?.voice?'ja':'nei/ukjent'} · SMS {item.exampleCapabilities?.sms?'ja':'nei/ukjent'} · MMS {item.exampleCapabilities?.mms?'ja':'nei/ukjent'} · adressekrav {item.addressRequirements??'bekreft ved valgt nummer'}</Text></View>)}
 <Text style={{color:t.color.muted,fontSize:12,lineHeight:18}}>Utgående internasjonal tale: {country?.outboundVoicePolicyEnabled?'aktivert i Vedøy-policy':'ikke aktivert i Vedøy-policy'}. SMS: {country?.outboundSmsPolicyEnabled?'aktivert i Vedøy-policy':'ikke aktivert i Vedøy-policy'}. Twilio-rutetillatelse og destinasjonspris må også være gyldig.</Text><Field value={query} onChangeText={setQuery} placeholder="Nummermønster (valgfritt)"/><Button title="Søk tilgjengelige numre  ↗" onPress={search} loading={busy} disabled={!country?.numberSearchAvailable||!country?.numberTypes.includes(type)}/></Card>
 {notice?<Text accessibilityLiveRegion="polite" style={{color:t.color.amber,lineHeight:21}}>{notice}</Text>:null}<Label>RESULTATER</Label>{numbers.map(n=><Card key={n.phoneNumber} style={{gap:9}}><Text style={{color:t.color.text,fontSize:20,fontWeight:'800'}}>{n.friendlyName||n.phoneNumber}</Text><Text style={{color:t.color.muted}}>{n.locality||country?.country} · {n.addressRequirements==='none'?'Ingen adressekrav vist':`Adressekrav: ${n.addressRequirements}`}</Text><Text style={{color:t.color.green,fontSize:13}}>SMS {n.capabilities.sms?'✓':'—'}   Tale {n.capabilities.voice?'✓':'—'}   MMS {n.capabilities.mms?'✓':'—'}</Text><Text style={{color:t.color.text,fontSize:15,fontWeight:'800'}}>{n.monthlyPrice&&n.currency?`${n.monthlyPrice} ${n.currency} / måned`:'Månedspris ikke tilgjengelig'}</Text><Button title="Se pris og lei nummer" secondary onPress={()=>buy(n)} disabled={busy||!n.monthlyPrice||!n.currency}/></Card>)}
 <Card style={{gap:7}}><Text style={{color:t.color.text,fontWeight:'800'}}>Hva prisen betyr</Text><Text style={{color:t.color.muted,lineHeight:21}}>Månedsprisen gjelder Twilio-nummeret og belastes den tilknyttede Twilio-kontoen. Samtaler og meldinger kommer i tillegg. Denne grunnversjonen tar ikke betaling fra Vedoy-kunder eller utsteder egne fakturaer. Nummerets land avgjør heller ikke internasjonale ruter. Mobildata er ikke inkludert.</Text></Card></ScrollView></SafeAreaView>
}
