import React,{useCallback,useState} from 'react';
import { Alert,Pressable,ScrollView,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useFocusEffect } from 'expo-router';
import { Card,PageTitle } from '../../components/ui';
import { theme as t } from '../../theme';
import { signOut } from '../../lib/auth';
import { api } from '../../lib/api';
type Line={id:string;phone_number:string;country_code:string;number_type:string;capabilities:{voice:boolean;sms:boolean;mms:boolean};status:string};
export default function Account(){const [lines,setLines]=useState<Line[]>([]);const [notice,setNotice]=useState('');const refresh=useCallback(()=>api<{numbers:Line[]}>('/v1/numbers/mine').then(x=>setLines(x.numbers)).catch(()=>{}),[]);useFocusEffect(useCallback(()=>{refresh()},[refresh]));function release(line:Line){Alert.alert('Frigi linje?',`${line.phone_number} kan ikke brukes videre, og Twilio-leiebeløp vil stoppe når frigivelsen er fullført.`,[{text:'Avbryt',style:'cancel'},{text:'Frigi linje',style:'destructive',onPress:async()=>{try{await api(`/v1/numbers/mine/${line.id}`,{method:'DELETE'});setNotice(`${line.phone_number} er frigitt.`);await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Kunne ikke frigi nummeret')}}}])}async function logout(){try{await signOut();router.replace('/auth')}catch(error){Alert.alert('Kunne ikke logge ut',error instanceof Error?error.message:'Prøv igjen senere.')}}return <SafeAreaView style={{flex:1,backgroundColor:t.color.bg}}><ScrollView contentContainerStyle={{padding:22,gap:14}}><PageTitle eyebrow="KONTO" title="Innstillinger" sub="Administrer de virtuelle linjene og identiteten din."/><Card style={{gap:13}}><Text style={{color:t.color.text,fontSize:18,fontWeight:'800'}}>Mine linjer · {lines.length}</Text>{lines.map(l=><View key={l.id} style={{paddingTop:12,borderTopColor:t.color.border,borderTopWidth:1,gap:6}}><Text style={{color:t.color.text,fontWeight:'700'}}>{l.phone_number} · {l.country_code}</Text><Text style={{color:t.color.muted,fontSize:12}}>{l.number_type} · SMS {l.capabilities.sms?'✓':'—'} · Tale {l.capabilities.voice?'✓':'—'} · MMS {l.capabilities.mms?'✓':'—'}</Text><Pressable onPress={()=>release(l)}><Text style={{color:t.color.danger,fontWeight:'700',marginTop:5}}>Frigi linje</Text></Pressable></View>)}{!lines.length?<Text style={{color:t.color.muted}}>Ingen aktive linjer ennå. Finn et nummer i Nummerbutikken.</Text>:null}</Card>{notice?<Text style={{color:t.color.amber}}>{notice}</Text>:null}<Card><Text onPress={()=>router.push('/kyc')} style={{color:t.color.text,fontSize:17,fontWeight:'700'}}>Identitet og dokumenter  ↗</Text><Text style={{color:t.color.muted,marginTop:8}}>Kontroller verifiseringsstatus og send inn nødvendige filer.</Text></Card><Card><Text onPress={()=>router.push('/api-info')} style={{color:t.color.text,fontSize:17,fontWeight:'700'}}>Tilkoblingsstatus  ↗</Text></Card><Card><Text onPress={()=>void logout()} style={{color:t.color.danger,fontWeight:'700'}}>Logg ut</Text></Card><Text style={{color:t.color.dim,textAlign:'center'}}>Vedoy Connect · Communications</Text></ScrollView></SafeAreaView>}
