import React from 'react';
import { Alert,Linking,Platform,ScrollView,Text,View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button,Card,PageTitle } from '../../components/ui';
import { appShortcuts } from '../../lib/appShortcuts';
import { theme as t } from '../../theme';

async function open(url:string){try{await Linking.openURL(url)}catch{Alert.alert('Kunne ikke åpne lenken','Kontroller at enheten har nettverk og prøv igjen.')}}
export default function Apps(){const featured=appShortcuts.find(app=>app.featured);const shortcuts=appShortcuts.filter(app=>!app.featured);return <SafeAreaView style={{flex:1,backgroundColor:t.color.bg}}><ScrollView contentContainerStyle={{padding:22,gap:14}}><PageTitle eyebrow="VEDØY · MOBIL" title="Dine apper" sub="Favorittverktøyene dine, samlet på ett sted."/>{featured?<Card style={{gap:15,backgroundColor:'#151126',borderColor:'#3A2B63'}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={{width:56,height:56,borderRadius:18,backgroundColor:'#24183B',alignItems:'center',justifyContent:'center'}}><Ionicons name={featured.icon as keyof typeof Ionicons.glyphMap} size={29} color={featured.accent}/></View><View style={{flex:1,gap:3}}><Text style={{color:t.color.text,fontSize:20,fontWeight:'900'}}>{featured.name}</Text><Text style={{color:featured.accent,fontSize:11,fontWeight:'800',letterSpacing:.7}}>DIN FAVORITT</Text></View><Ionicons name="arrow-up-circle-outline" size={24} color={featured.accent}/></View><Text style={{color:t.color.muted,fontSize:14,lineHeight:21}}>{featured.description}</Text><Button title={featured.cta??'Åpne'} onPress={()=>open(featured.openUrl)}/></Card>:null}<View style={{gap:11}}>{shortcuts.map(app=><Card key={app.id} style={{gap:11}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{width:44,height:44,borderRadius:14,backgroundColor:'#202823',alignItems:'center',justifyContent:'center'}}><Ionicons name={app.icon as keyof typeof Ionicons.glyphMap} size={23} color={app.accent}/></View><View style={{flex:1,gap:3}}><Text style={{color:t.color.text,fontSize:16,fontWeight:'800'}}>{app.name}</Text></View><Ionicons name="open-outline" size={17} color={t.color.dim}/></View><Text style={{color:t.color.muted,fontSize:13,lineHeight:19}}>{app.description}</Text><View style={{flexDirection:'row',gap:8}}><View style={{flex:1}}><Button title={app.cta??'Åpne'} onPress={()=>open(app.openUrl)}/></View>{app.kind==='Native app + web'?<View style={{flex:1}}><Button title={Platform.OS==='ios'?'App Store':'Google Play'} secondary onPress={()=>open(Platform.OS==='ios'?app.iosStore!:app.androidStore!)}/></View>:null}</View></Card>)}</View><Text style={{color:t.color.dim,fontSize:11,lineHeight:17,textAlign:'center'}}>Snarveiene åpnes trygt i appen eller nettleseren din.</Text></ScrollView></SafeAreaView>}
