import React,{useCallback,useEffect,useState} from 'react';
import { Pressable,ScrollView,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from 'expo-router';
import { Card,Field,Button,PageTitle,Label } from '../../components/ui';
import { theme as t } from '../../theme';
import { api } from '../../lib/api';
type Thread={phone:string;line:string;lastMessage:string;dateCreated:string};
type Message={twilio_sid:string;from_number:string;to_number:string;body:string;direction:'inbound'|'outbound';status:string;date_created:string};
type Line={id:string;phone_number:string;capabilities:{voice:boolean;sms:boolean;mms:boolean};status:string};
export default function ChatScreen(){
 const [threads,setThreads]=useState<Thread[]>([]),[lines,setLines]=useState<Line[]>([]),[selectedLine,setSelectedLine]=useState(''),[active,setActive]=useState(''),[history,setHistory]=useState<Message[]>([]),[to,setTo]=useState(''),[body,setBody]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const refreshThreads=useCallback(async()=>{try{const d=await api<{threads:Thread[]}>('/v1/messages/threads');setThreads(d.threads)}catch(e){setNotice(e instanceof Error?e.message:'Kunne ikke hente samtalene')}},[]);
 const refreshHistory=useCallback(async(peer:string,line:string)=>{if(!line)return;try{const d=await api<{messages:Message[]}>(`/v1/messages/threads/${encodeURIComponent(peer)}?line=${encodeURIComponent(line)}`);setHistory(d.messages)}catch(e){setNotice(e instanceof Error?e.message:'Kunne ikke hente meldinger')}},[]);
 useFocusEffect(useCallback(()=>{refreshThreads();api<{numbers:Line[]}>('/v1/numbers/mine').then(x=>{const capable=x.numbers.filter(n=>n.capabilities.sms&&n.status==='active');setLines(capable);setSelectedLine(current=>capable.some(n=>n.phone_number===current)?current:capable[0]?.phone_number??'')}).catch(()=>{})},[refreshThreads]));
 useEffect(()=>{if(!active||!selectedLine)return;refreshHistory(active,selectedLine);const timer=setInterval(()=>refreshHistory(active,selectedLine),8000);return()=>clearInterval(timer)},[active,selectedLine,refreshHistory]);
 async function send(){const recipient=active||to;if(!recipient.startsWith('+')||!body.trim()||!selectedLine)return;setBusy(true);setNotice('');try{await api('/v1/messages',{method:'POST',body:JSON.stringify({to:recipient,body,from:selectedLine})});setBody('');setActive(recipient);await refreshHistory(recipient,selectedLine);await refreshThreads()}catch(e){setNotice(e instanceof Error?e.message:'Kunne ikke sende')}finally{setBusy(false)}}
 const linePicker=<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{lines.map(l=><Pressable key={l.id} onPress={()=>setSelectedLine(l.phone_number)}><Text style={{color:selectedLine===l.phone_number?t.color.bg:t.color.text,backgroundColor:selectedLine===l.phone_number?t.color.green:t.color.raised,padding:9,borderRadius:10,overflow:'hidden'}}>{l.phone_number}</Text></Pressable>)}</View>;
 return <SafeAreaView style={{flex:1,backgroundColor:t.color.bg}}><ScrollView contentContainerStyle={{padding:22,gap:14}}>{active?<><Text onPress={()=>{setActive('');setHistory([])}} style={{color:t.color.green,fontWeight:'800'}}>‹ Alle tråder</Text><PageTitle eyebrow="SMS-TRÅD" title={active} sub="Oppdatert automatisk mens samtalen er åpen."/>{history.map(m=><View key={m.twilio_sid} style={{alignSelf:m.direction==='outbound'?'flex-end':'flex-start',maxWidth:'88%',backgroundColor:m.direction==='outbound'?'#24341E':t.color.surface,borderColor:t.color.border,borderWidth:1,borderRadius:18,padding:13}}><Text style={{color:t.color.text,lineHeight:21}}>{m.body}</Text><Text style={{color:t.color.muted,fontSize:10,marginTop:6}}>{m.status} · {new Date(m.date_created).toLocaleTimeString()}</Text></View>)}{history.length===0?<Card><Text style={{color:t.color.muted}}>Ingen meldinger i denne tråden ennå.</Text></Card>:null}<Card style={{gap:10}}>{linePicker}<Field value={body} onChangeText={setBody} placeholder="Skriv en melding…"/><Button title="Send" onPress={send} loading={busy} disabled={!selectedLine||!body.trim()}/></Card></>:<><PageTitle eyebrow="MELDINGER" title="Hold tråden" sub="To-veis SMS fra dine aktive Vedoy-numre."/><Card style={{gap:12}}><Label>NY SMS · FRA LINJE</Label>{linePicker}<Field value={to} onChangeText={setTo} placeholder="Mottaker · +4790000000" keyboardType="phone-pad"/><Field value={body} onChangeText={setBody} placeholder="Skriv en melding…"/><Button title="Send melding  ↗" onPress={send} loading={busy} disabled={!selectedLine||!to.startsWith('+')||!body.trim()}/></Card><Label>SISTE TRÅDER</Label>{threads.map(x=><Pressable key={`${x.line}:${x.phone}`} onPress={()=>{setSelectedLine(x.line);setActive(x.phone)}}><Card><Text style={{color:t.color.text,fontWeight:'800'}}>{x.phone} · {x.line}</Text><Text style={{color:t.color.muted,marginTop:7}} numberOfLines={2}>{x.lastMessage}</Text></Card></Pressable>)}{threads.length===0?<Card><Text style={{color:t.color.muted}}>Meldingene dine vises her. Velg et SMS-kompatibelt nummer for å starte.</Text></Card>:null}</>}{notice?<Text style={{color:t.color.amber}}>{notice}</Text>:null}</ScrollView></SafeAreaView>
}
