import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import {rateLimit} from 'express-rate-limit';
import {env} from './config.js';
import {requireAuth} from './auth.js';
import {asyncRoute} from './http.js';
import {numbers} from './numbers.js';
import {messages,twilioSms} from './messages.js';
import {voice,twilioVoice} from './voice.js';
import {kyc} from './kyc.js';
const app=express();
app.disable('x-powered-by');app.set('trust proxy',1);app.use(helmet());
const origins=env.APP_ORIGINS.split(',').map(x=>x.trim()).filter(Boolean);app.use(cors({origin:(origin,cb)=>{if(!origin||origins.includes(origin))return cb(null,true);cb(new Error('Origin not allowed'))},credentials:true}));
app.use('/webhooks/twilio',express.urlencoded({extended:false,limit:'64kb'}));app.use(express.json({limit:'32kb'}));
app.get('/health',(_req,res)=>res.json({ok:true,service:'vedoy-connect-api'}));
const apiLimit=rateLimit({windowMs:60_000,limit:120,standardHeaders:true,legacyHeaders:false});app.use('/v1',apiLimit,requireAuth);
app.use('/v1/numbers',numbers);app.use('/v1/messages',messages);app.use('/v1/voice',voice);app.use('/v1/kyc',kyc);
app.use('/webhooks/twilio/voice',twilioVoice);app.use('/webhooks/twilio/sms',twilioSms);
app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error('request_failed',err instanceof Error?{name:err.name,message:env.NODE_ENV==='production'?'redacted':err.message}:err);res.status(500).json({message:'Noe gikk galt. Prøv igjen eller kontakt støtte.'})});
app.listen(env.PORT,'0.0.0.0',()=>console.log(`Vedoy Connect API listening on ${env.PORT}`));
