import {Router} from 'express';
import {z} from 'zod';
import countryData from 'i18n-iso-countries';
import english from 'i18n-iso-countries/langs/en.json' with {type:'json'};
import {db,twilioClient} from './clients.js';
import {env} from './config.js';
import {asyncRoute,e164} from './http.js';
import {phoneNumberPrices} from './pricing.js';
export const numbers=Router();
countryData.registerLocale(english);
const types=['local','mobile','tollFree'] as const;
type NumberType=(typeof types)[number];
type SearchResult={phoneNumber:string;friendlyName:string;locality:string|null;capabilities:{voice:boolean;sms:boolean;mms:boolean};addressRequirements:string};
async function listNumbers(country:string,type:NumberType,opts:{limit?:number;contains?:string}):Promise<SearchResult[]>{const r=twilioClient.availablePhoneNumbers(country);const items=type==='local'?await r.local.list(opts):type==='mobile'?await r.mobile.list(opts):await r.tollFree.list(opts);return items.map(n=>({phoneNumber:n.phoneNumber,friendlyName:n.friendlyName,locality:n.locality,capabilities:n.capabilities,addressRequirements:n.addressRequirements}))}
numbers.get('/mine',asyncRoute(async(req,res)=>{const {data,error}=await db.from('phone_numbers').select('id,phone_number,country_code,number_type,capabilities,status,created_at').eq('user_id',req.userId!).in('status',['active','pending']).order('created_at',{ascending:true});if(error)throw error;res.json({numbers:data??[]})}));
numbers.delete('/mine/:id',asyncRoute(async(req,res)=>{const id=String(req.params.id??'');const {data,error}=await db.from('phone_numbers').select('id,twilio_sid').eq('id',id).eq('user_id',req.userId!).eq('status','active').single();if(error||!data)return res.status(404).json({message:'Fant ikke en aktiv linje på kontoen.'});if(!data.twilio_sid)return res.status(409).json({message:'Linjen mangler Twilio-referanse.'});await twilioClient.incomingPhoneNumbers(data.twilio_sid).remove();const updated=await db.from('phone_numbers').update({status:'released',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',req.userId!);if(updated.error)throw updated.error;res.sendStatus(204)}));
numbers.get('/countries',asyncRoute(async(_req,res)=>{const list=await twilioClient.availablePhoneNumbers.list({limit:1000});const byCode=new Map(list.map(c=>[c.countryCode,c]));const voicePolicy=new Set(env.VOICE_ALLOWED_COUNTRIES.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean));const smsPolicy=new Set(env.SMS_ALLOWED_COUNTRIES.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean));const countries=Object.keys(countryData.getAlpha2Codes()).map(countryCode=>{const twilioCountry=byCode.get(countryCode);return {countryCode,country:twilioCountry?.country??countryData.getName(countryCode,'en')??countryCode,numberTypes:Object.keys(twilioCountry?.subresourceUris??{}).filter(k=>types.includes(k as typeof types[number])),numberSearchAvailable:!!twilioCountry,outboundVoicePolicyEnabled:voicePolicy.has(countryCode),outboundSmsPolicyEnabled:smsPolicy.has(countryCode),mobileData:false,providerGeoPermissionMustAlsoBeEnabled:true,regulatoryRequirements:'Check against each number type before purchase'}}).sort((a,b)=>a.country.localeCompare(b.country));res.json({countries,source:'ISO country list + live account-scoped Twilio number catalog',outboundPolicy:'Vedoy allowlist; Twilio geo permissions and destination rates are separate'})}));
numbers.get('/countries/:code/capabilities',asyncRoute(async(req,res)=>{const country=String(req.params.code??'').toUpperCase();if(!/^[A-Z]{2}$/.test(country))return res.status(400).json({message:'Ugyldig landkode.'});const parent=await twilioClient.availablePhoneNumbers(country).fetch();const rows=await Promise.all(Object.keys(parent.subresourceUris??{}).filter(k=>types.includes(k as NumberType)).map(async t=>{const list=await listNumbers(country,t as NumberType,{limit:1});const n=list[0];return {type:t,available:!!n,exampleCapabilities:n?.capabilities??null,addressRequirements:n?.addressRequirements??null}}));res.json({countryCode:country,country:parent.country,numberTypes:rows,internationalVoice:'Check the Twilio destination route and account geo-permissions separately.',internationalSms:'Check sender-country and destination delivery requirements separately.',mobileData:false,note:'Example capabilities are a live sample only. Always use the selected number’s own capability and regulatory metadata.'})}));
numbers.get('/countries/:code/pricing',asyncRoute(async(req,res)=>{const code=String(req.params.code??'').toUpperCase();if(!/^[A-Z]{2}$/.test(code))return res.status(400).json({message:'Ugyldig landkode.'});res.json({countryCode:code,prices:await phoneNumberPrices(code),billing:'Monthly Twilio recurring number charge; usage billed separately.'})}));
numbers.get('/available',asyncRoute(async(req,res)=>{const parsed=z.object({country:z.string().length(2).transform(x=>x.toUpperCase()),type:z.enum(types).default('local'),contains:z.string().max(16).optional()}).safeParse(req.query);if(!parsed.success)return res.status(400).json({message:'Velg en gyldig landkode og nummertype.'});const {country,type,contains}=parsed.data;const [list,priceResult]=await Promise.all([listNumbers(country,type,{limit:env.MAX_NUMBER_SEARCH_RESULTS,...(contains?{contains}:{})}),phoneNumberPrices(country).catch(()=>({} as Record<string,import('./pricing.js').Price>))]);const prices:Record<string,import('./pricing.js').Price>=priceResult;res.json({numbers:list.map(n=>({...n,numberType:type,countryCode:country,monthlyPrice:prices[type]?.monthlyPrice??null,currency:prices[type]?.currency??null})),mobileData:false})}));
numbers.post('/purchase',asyncRoute(async(req,res)=>{const input=z.object({phoneNumber:z.string().refine(e164),countryCode:z.string().length(2).transform(x=>x.toUpperCase()),numberType:z.enum(types),confirmedMonthlyPrice:z.string().min(1),currency:z.string().length(3)}).safeParse(req.body);if(!input.success)return res.status(400).json({message:'Bekreft månedlig pris før kjøp.'});const user=req.userId!;const latestPrices=await phoneNumberPrices(input.data.countryCode).catch(()=>null);const current=latestPrices?.[input.data.numberType];if(!current)return res.status(503).json({message:'Fant ikke en oppdatert pris. Prøv igjen senere.'});if(current.monthlyPrice!==input.data.confirmedMonthlyPrice||current.currency!==input.data.currency.toUpperCase())return res.status(409).json({message:'Månedsprisen er endret. Kontroller prisen før du prøver på nytt.',current});
  const found=await listNumbers(input.data.countryCode,input.data.numberType,{contains:input.data.phoneNumber,limit:100});const n=found.find(x=>x.phoneNumber===input.data.phoneNumber);if(!n)return res.status(409).json({message:'Nummeret er ikke lenger tilgjengelig.'});
  let regulatoryAddressSid:string|undefined;if(n.addressRequirements!=='none'){const {data:kyc}=await db.from('kyc_submissions').select('id,status,twilio_address_sid,twilio_compliance_complete').eq('user_id',user).eq('status','approved').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!kyc||!kyc.twilio_compliance_complete)return res.status(403).json({message:'Dette nummeret krever godkjent dokumentasjon og gjennomført Twilio-compliance før aktivering.'});if(n.addressRequirements!=='none'&&!kyc.twilio_address_sid)return res.status(503).json({message:'KYC-godkjenningen mangler en Twilio-adresse.'});regulatoryAddressSid=kyc.twilio_address_sid??undefined}
  const reservation=await db.rpc('reserve_phone_number',{p_user_id:user,p_phone_number:input.data.phoneNumber,p_country_code:input.data.countryCode,p_number_type:input.data.numberType,p_capabilities:n.capabilities,p_max:env.MAX_NUMBERS_PER_USER});if(reservation.error){if(/number_limit|duplicate key/i.test(reservation.error.message))return res.status(409).json({message:reservation.error.message.includes('number_limit')?`Kontogrensen er ${env.MAX_NUMBERS_PER_USER} aktive numre.`:'Nummeret er allerede knyttet til en konto.'});throw reservation.error}const reservationId=reservation.data as string;
  let provisionedSid:string|undefined;
  try{const number=await twilioClient.incomingPhoneNumbers.create({phoneNumber:input.data.phoneNumber,voiceUrl:`${env.PUBLIC_BASE_URL}/webhooks/twilio/voice`,voiceMethod:'POST',smsUrl:`${env.PUBLIC_BASE_URL}/webhooks/twilio/sms/inbound`,smsMethod:'POST',statusCallback:`${env.PUBLIC_BASE_URL}/webhooks/twilio/voice/status`,statusCallbackMethod:'POST',...(regulatoryAddressSid?{addressSid:regulatoryAddressSid}:{})});provisionedSid=number.sid;const updated=await db.from('phone_numbers').update({twilio_sid:number.sid,status:'active',updated_at:new Date().toISOString()}).eq('id',reservationId).eq('user_id',user).select('id').single();if(updated.error)throw updated.error;res.status(201).json({id:reservationId,phoneNumber:number.phoneNumber,status:'active',capabilities:number.capabilities})}catch(e){if(provisionedSid){try{await twilioClient.incomingPhoneNumbers(provisionedSid).remove()}catch(cleanupError){console.error('number_cleanup_failed',{reservationId,provisionedSid,error:cleanupError});await db.from('phone_numbers').update({twilio_sid:provisionedSid,status:'pending',updated_at:new Date().toISOString()}).eq('id',reservationId);throw e}}await db.from('phone_numbers').update({status:'failed',updated_at:new Date().toISOString()}).eq('id',reservationId);throw e}
}));
