import {Router} from 'express';
import {z} from 'zod';
import twilio,{jwt} from 'twilio';
import {db,twilioClient} from './clients.js';
import {env} from './config.js';
import {asyncRoute,destinationAllowed,e164,validateTwilio} from './http.js';
const {AccessToken}=jwt;
export const voice=Router();
voice.post('/token',asyncRoute(async(req,res)=>{const platform=req.body?.platform==='ios'?'ios':req.body?.platform==='android'?'android':null;if(!platform)return res.status(400).json({message:'Enhetsplattform mangler.'});const identity=`v_${req.userId!.replace(/-/g,'')}`;const token=new AccessToken(env.TWILIO_ACCOUNT_SID,env.TWILIO_API_KEY,env.TWILIO_API_SECRET,{identity,ttl:3600});const pushCredentialSid=platform==='ios'?env.TWILIO_IOS_PUSH_CREDENTIAL_SID:env.TWILIO_ANDROID_PUSH_CREDENTIAL_SID;token.addGrant(new AccessToken.VoiceGrant({outgoingApplicationSid:env.TWILIO_TWIML_APP_SID,incomingAllow:!!pushCredentialSid,...(pushCredentialSid?{pushCredentialSid}:{})}));res.json({token:token.toJwt(),identity,expiresIn:3600,incomingConfigured:!!pushCredentialSid})}));
voice.get('/history',asyncRoute(async(req,res)=>{const {data,error}=await db.from('call_events').select('call_sid,status,direction,from_number,to_number,duration_seconds,updated_at').eq('user_id',req.userId!).order('updated_at',{ascending:false}).limit(100);if(error)throw error;res.json({calls:data??[]})}));
export const twilioVoice=Router();
twilioVoice.post('/',validateTwilio,asyncRoute(async(req,res)=>{const from=String(req.body.From??'');const to=String(req.body.To??'');const callerId=String(req.body.CallerId??'');const twiml=new twilio.twiml.VoiceResponse();if(from.startsWith('client:')){const userId=await userForIdentity(from.slice(7));if(!userId)return res.status(403).send('Unknown client');if(!e164(to))return res.status(400).send('Invalid destination');if(!destinationAllowed(to,env.VOICE_ALLOWED_COUNTRIES))return res.status(403).send('Destination country is not enabled for this service');let ownedQuery=db.from('phone_numbers').select('phone_number,capabilities').eq('user_id',userId).eq('status','active').eq('capabilities->>voice','true');if(callerId)ownedQuery=ownedQuery.eq('phone_number',callerId);const owned=await ownedQuery.order('created_at').limit(1).maybeSingle();if(!owned.data?.capabilities?.voice)return res.status(403).send('No active voice-capable number');const dial=twiml.dial({callerId:owned.data.phone_number,answerOnBridge:true,action:`${env.PUBLIC_BASE_URL}/webhooks/twilio/voice/status`,method:'POST'});dial.number({statusCallback:`${env.PUBLIC_BASE_URL}/webhooks/twilio/voice/status`,statusCallbackEvent:['initiated','ringing','answered','completed']},to)}else{const owned=await db.from('phone_numbers').select('user_id,capabilities').eq('phone_number',to).eq('status','active').maybeSingle();if(!owned.data)return res.status(404).send('Number is not active');if(!owned.data.capabilities?.voice)return res.status(403).send('Voice unsupported');const identity=`v_${owned.data.user_id.replace(/-/g,'')}`;twiml.dial({action:`${env.PUBLIC_BASE_URL}/webhooks/twilio/voice/status`,method:'POST'}).client(identity)}res.type('text/xml').send(twiml.toString())}));
twilioVoice.post('/status',validateTwilio,asyncRoute(async(req,res)=>{const callSid=String(req.body.CallSid??req.body.ParentCallSid??'');const status=String(req.body.CallStatus??req.body.DialCallStatus??'');const from=String(req.body.From??''),to=String(req.body.To??'');let userId=from.startsWith('client:')?await userForIdentity(from.slice(7)):null;if(!userId){const {data}=await db.from('phone_numbers').select('user_id').eq('phone_number',from).eq('status','active').maybeSingle();userId=data?.user_id??null}if(!userId){const {data}=await db.from('phone_numbers').select('user_id').eq('phone_number',to).eq('status','active').maybeSingle();userId=data?.user_id??null}if(callSid&&userId)await db.from('call_events').upsert({call_sid:callSid,user_id:userId,status,direction:String(req.body.Direction??''),from_number:from,to_number:to,duration_seconds:Number(req.body.CallDuration??req.body.DialCallDuration)||null,updated_at:new Date().toISOString()},{onConflict:'call_sid'});res.sendStatus(204)}));
async function userForIdentity(identity:string){const match=/^v_([0-9a-f]{32})$/i.exec(identity);if(!match)return null;const hex=match[1]!.toLowerCase();const userId=[hex.slice(0,8),hex.slice(8,12),hex.slice(12,16),hex.slice(16,20),hex.slice(20)].join('-');const {data}=await db.from('phone_numbers').select('user_id').eq('user_id',userId).eq('status','active').limit(1).maybeSingle();return data?.user_id??null}
