export type AppShortcut={id:string;name:string;description:string;kind:'Native app + web'|'Mobilnettsted'|'Desktop-funksjon';icon:string;accent:string;openUrl:string;iosStore?:string;androidStore?:string;alternateUrl?:string;featured?:boolean;cta?:string};
/** External mobile destinations. These are shortcuts only; they do not link accounts or share credentials. */
export const appShortcuts:AppShortcut[]=[
 {id:'autocalls',name:'Autocalls AI',description:'Start AI-drevne telefonsamtaler, agentflyter og kampanjer fra mobilen.',kind:'Mobilnettsted',icon:'radio-outline',accent:'#A78BFA',openUrl:'https://app.autocalls.ai/',featured:true,cta:'Åpne Autocalls'},
 {id:'wix',name:'Wix',description:'Administrer nettsted, innboks og virksomhet',kind:'Native app + web',icon:'globe-outline',accent:'#4EA1FF',openUrl:'https://manage.wix.com/',iosStore:'https://apps.apple.com/no/app/wix-website-builder/id1545924344',androidStore:'https://play.google.com/store/apps/details?id=com.wix.admin'},
 {id:'openai',name:'OpenAI Developers',description:'Utviklerdokumentasjon og API-plattform',kind:'Mobilnettsted',icon:'code-slash-outline',accent:'#72D7AD',openUrl:'https://developers.openai.com/',alternateUrl:'https://platform.openai.com/'},
 {id:'chatgpt',name:'ChatGPT',description:'OpenAI-appen for samtaler og assistanse',kind:'Native app + web',icon:'chatbubbles-outline',accent:'#72D7AD',openUrl:'https://chatgpt.com/',iosStore:'https://apps.apple.com/no/app/chatgpt/id6448311069',androidStore:'https://play.google.com/store/apps/details?id=com.openai.chatgpt'},
 {id:'supabase',name:'Supabase',description:'Prosjekter, database, Auth og Storage',kind:'Mobilnettsted',icon:'layers-outline',accent:'#58D68D',openUrl:'https://supabase.com/dashboard'},
 {id:'vercel',name:'Vercel',description:'Deployments, prosjekter og logger',kind:'Mobilnettsted',icon:'triangle-outline',accent:'#F3F4F6',openUrl:'https://vercel.com/dashboard'},
 {id:'twilio',name:'Twilio Console',description:'Numre, Voice, Messaging og forbruk',kind:'Mobilnettsted',icon:'call-outline',accent:'#F56565',openUrl:'https://console.twilio.com/'},
 {id:'computer',name:'Computer',description:'Datamaskinstyring må startes fra ChatGPT/Codex på en støttet desktop. Denne snarveien åpner ChatGPT; den aktiverer ikke skjermstyring på mobilen.',kind:'Desktop-funksjon',icon:'desktop-outline',accent:'#F6C453',openUrl:'https://chatgpt.com/'},
];
